//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POGPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public long Id { get; set; }
        public string RoleName { get; set; }
        public string MenuCode { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
    }
}
